spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 12345

  logging:
    level:
      org.springframework: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      com.ApiForFoodApp.demo: DEBUG

  # JPA SETTINGS
  jpa:
    hibernate:
      ddl_auto: update


